### ISSUE TITLE
Update to tmux 3.2

### ISSUE THREAD

**Issue by XhstormR** [conda-forge/tmux-feedstock#23]
The new version has been released for several months.

https://github.com/tmux/tmux/releases/tag/3.2a

**Comment by jakirkham** [comment]
Yeah there's a PR for this already ( https://github.com/conda-forge/tmux-feedstock/pull/22 ), but it fails on macOS ARM ( https://github.com/conda-forge/tmux-feedstock/pull/22#issuecomment-912914724 ). Probably going to need some help from someone else who knows macOS ARM better to move that forward

**Comment by XhstormR** [comment]
@jakirkham Is there any update?

**Comment by jakirkham** [comment]
No additional updates beyond the comment above. If you have time to look into the macOS ARM build issue, that would be appreciated. Unfortunately haven't had time or resources needed to dig into that further atm

**Comment by jakirkham** [comment]
Update to 3.2a in PR ( https://github.com/conda-forge/tmux-feedstock/pull/26 )
