### ISSUE TITLE
rebuild against ncurses 6.1

### ISSUE THREAD

**Issue by lebedov** [conda-forge/tmux-feedstock#8]
Would it be possible to rebuild tmux against ncurses 6.1? It's current dependency on ncurses 5.9 prevents it from being installed simultaneously with packages that depend on ncurses 6.1 such as emacs 26.1-h3a2ea38_1.

**Comment by asmeurer** [comment]
Looks like this PR does this, but it has some build failures. https://github.com/conda-forge/tmux-feedstock/pull/7

**Comment by jakirkham** [comment]
On holiday currently, feel free to submit fixes to this feedstock and can review once I get back. Thanks.

**Comment by lebedov** [comment]
The sha256 key isn't valid - should be updated to 89e4774db7d238b1ee515c4527ef90153f0c3cd8ad3e3fde5c01fbbb27fd01a6

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/tmux-feedstock/pull/7 ).
